; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	RotaryEncoder
	gavinlyonsrepo/TM1638plus @ ^2.2.0
	x385832/Elog@^2.0.17
	igorantolic/Ai Esp32 Rotary Encoder@^1.7
	thomasfredericks/Bounce2@^2.72
build_flags = -DCORE_DEBUG_LEVEL=0
monitor_speed = 115200
