#ifndef CONFIG_H
#define CONFIG_H

// Pin definitions
#define RELAY_PIN 32    // relay #1 controls the enlarger light
#define TM1638_DIO 21   // TM1638 data pin 
#define TM1638_CLK 22   // TM1638 clock pin
#define TM1638_STB 23   // TM1638 strobe pin
#define ENCODER1_CLK 15
#define ENCODER1_DT 16
#define ENCODER1_SW 14
#define ENCODER1_VCC -1
#define ENCODER1_STEPS 4

#define ENCODER2_CLK 19
#define ENCODER2_DT 18
#define ENCODER2_SW 17
#define ENCODER2_VCC -1
#define ENCODER2_STEPS 4

// Constants
#define BASE_TIME_DEFAULT 10.0f
#define BASE_FSTOP_DEFAULT 0

#define MODE_BUTTON 0x01 // Bitmask for mode button on TM1638

#define MYLOG 0

/**
 * @brief Message type codes for input and control events
 *
 * These values are used in queued messages to describe the type of
 * event generated by buttons and rotary encoders.
 */
enum MsgType {
    MODE_BUTTON_PRESS,   /**< Mode button pressed on TM1638 */
    BUTTON_VALUE_PRESS,   /**< Value encoder button pressed */
    BUTTON_MODE_PRESS,    /**< Mode encoder button pressed */
    ENCODER_VALUE_CHANGE, /**< Value encoder rotation changed */
    ENCODER_MODE_CHANGE,   /**< Mode encoder rotation changed */
    TIME_TICK            /**< Timer tick event for exposure timing */
};

/**
 * @brief Queue item structure for inter-task communication
 *
 * This structure is sent over FreeRTOS queues to communicate input events
 * between tasks, including the message type and optional payload data.
 */
struct QueueItem {
    MsgType type;   /**< Type of message/event */
    void* payload;  /**< Optional pointer to additional data (for example encoder value) */
};
#endif