#ifndef CONFIG_H
#define CONFIG_H

// Pin definitions
#define RELAY_PIN 32    // relay #1 controls the enlarger light
#define TM1638_DIO 21   // TM1638 data pin 
#define TM1638_CLK 22   // TM1638 clock pin
#define TM1638_STB 23   // TM1638 strobe pin
#define ENCODER1_CLK 15
#define ENCODER1_DT 16
#define ENCODER1_SW 14
#define ENCODER1_VCC -1
#define ENCODER1_STEPS 4

#define ENCODER2_CLK 19
#define ENCODER2_DT 18
#define ENCODER2_SW 17
#define ENCODER2_VCC -1
#define ENCODER2_STEPS 4

#define BEEPER_PIN 25 // GPIO pin for the beeper

// Constants
#define BASE_TIME_DEFAULT 10.0f
#define BASE_FSTOP_DEFAULT 0

#define MODE_BUTTON 0x01 // Bitmask for mode button on TM1638
#define CANCEL_BUTTON 0x02 // Bitmask for cancel button on TM1638
#define ITERATIVE_BUTTON 0x04 // Bitmask for button toggling between iterative and single step exposure mode for test strip sequence 

#define MYLOG 0

#define MIN_STEP -3  /**< Minimum step value */
#define MAX_STEP 3   /**< Maximum step value */
#define NUM_STEPS (MAX_STEP - MIN_STEP + 1) /**< Total number of steps */

#define MIN_GRANULARITY 0 /**< Minimum granularity value (for example, 0 could represent 1 stop) */
#define MAX_GRANULARITY 4 /**< Maximum granularity value (for example, 4 could represent 1/12 stop) */
#define NUM_GRANULARITY_LEVELS (MAX_GRANULARITY - MIN_GRANULARITY + 1) /**< Total number of granularity levels */

#define MIN_EXPOSURE_TIME 0     /**< Minimum exposure time in seconds */
#define MAX_EXPOSURE_TIME 999   /**< Maximum exposure time in seconds */

#define MAX_DISPLAY_STR_LEN 10 // 8 characters + eventual decimal points + null terminator

#define WAIT_BETWEEN_TEST_STRIP_STEPS_MS 2000 // Time to wait between test strip steps in milliseconds



/**
 * @brief Message type codes for input and control events
 *
 * These values are used in queued messages to describe the type of
 * event generated by buttons and rotary encoders.
 */
enum MsgType {
    MODE_CHANGED,       /**< Message to update the display after the mode has changed to a new one */
    MODE_BUTTON_PRESS,   /**< Mode button pressed on TM1638 */
    CANCEL_BUTTON_PRESS, /**< Cancel button pressed on TM1638 */
    ITERATIVE_BUTTON_PRESS, /**< Iterative button pressed on TM1638 */
    FOOT_SWITCH_PRESS,    /**< Foot switch pressed (if applicable) */
    BUTTON_VALUE_PRESS,   /**< Value encoder button pressed */
    BUTTON_MODE_PRESS,    /**< Mode encoder button pressed */
    ENCODER_VALUE_CHANGE, /**< Value encoder rotation changed */
    ENCODER_MODE_CHANGE,   /**< Mode encoder rotation changed */
    TIME_ELAPSED,          /**< Exposure timer has elapsed */
    TIME_TICK            /**< Timer tick event for exposure timing */
};

/**
 * @brief States for the finite state machine
 */
enum State {
    INITIAL,                /**< Initial state with welcome message */
    FOCUS_LIGHT_OFF,        /**< Focus light is off */
    FOCUS_LIGHT_ON,         /**< Focus light is on */
    TEST_STRIP_CONFIG,      /**< Configuring test strip parameters */
    TEST_STRIP_SEQUENCE,    /**< Running test strip exposure sequence */
    FSTOP_EXPOSURE_CONFIG,  /**< Configuring f-stop exposure parameters */
    FSTOP_EXPOSURE,          /**< Performing f-stop exposure */
    TIME_EXPOSURE_CONFIG,   /**< Configuring time-based exposure parameters */
    TIME_EXPOSURE           /**< Performing time-based exposure */
};

/**
 * @brief Queue item structure for inter-task communication
 *
 * This structure is sent over FreeRTOS queues to communicate input events
 * between tasks, including the message type and optional payload data.
 */
struct QueueItem {
    MsgType type;   /**< Type of message/event */
    void* payload;  /**< Optional pointer to additional data (for example encoder value) */
};
#endif